image:
  - Visual Studio 2015
version: "{build}"
clone_depth: 1

# scripts that are called at very beginning, before repo cloning
init:
- git config --global core.longpaths true
- git config --global core.autocrlf input

branches:
  only:
     - master
     
install:
- cmd: SET PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\;%PATH%
- rename "C:\Program Files\Git\usr\bin\sh.exe" "sh-ignored.exe"
environment:
  matrix:
    - BUILD_TYPE: Release
      COMPILER: MinGW-w64
      PLATFORM: x64
    - BUILD_TYPE: Debug
      COMPILER: MinGW-w64
      PLATFORM: x64

build_script:
- cd Build
- cd %BUILD_TYPE%
- set PATH
- cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ../../
- mingw32-make
- mingw32-make install

test_script:
- ctest --output-on-failure
